<?php
/**
 * Created by PhpStorm.
 * User: Vitaut
 * Date: 10.05.2017
 * Time: 19:34
 */

namespace app\controllers;
use Yii;
use app\controllers\Base\MainController as MainController;
use yii\web\NotFoundHttpException;
use app\models\User;
class ProfileController extends MainController
{
    private $user_id;
    public $slaidshow;
    public $slug;
    /*
     * Псевдоконструктор
     */
    public function beforeAction($action)
    {
        $this->user_id= Yii::$app->user->identity->getId();
        // Получіть роль, родітельскій метод
      //  $this->getRole();
        //
        $this->slaidshow=null;
        $this->slug= "profile";
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {



       $model =User::findOne($this->user_id);
        return $this->render('index', [
            'model' => $model,

        ]);
    }

//    public function actionUpdate () {
//        echo 9;
//        die();
//        $model = $this->findModel($id);
//
//        if ($model->load(Yii::$app->request->post()) && $model->save()) {
//            return $this->redirect(['view', 'id' => $model->id]);
//        } else {
//            return $this->render('update', [
//                'model' => $model,
//            ]);
//        }
//    }

}