<?php

namespace app\models\base;

use Yii;
use app\models\ProductsServices;
/**
 * This is the model class for table "products".
 *
 * @property integer $id
 * @property string $title
 * @property string $price
 * @property string $description
 * @property string $cashback
 * @property integer $casino_id
 *
 * @property Casino $casino
 */
class Products extends \yii\db\ActiveRecord
{
    public $service_id;
    /**
     * @inheritdoc
     */
  public function __construct(array $config = [])
  {
      $this->service_id=null;
      parent::__construct($config);
  }

    public static function tableName()
    {
        return 'products';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'meta_keywords', 'meta_description', 'description'], 'string'],
            [['price', 'cashback'], 'string'],
            [['casino_id'], 'number'],
            [['casino_id'], 'exist', 'skipOnError' => true, 'targetClass' => Casino::className(), 'targetAttribute' => ['casino_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'meta_description' => 'Meta Description',
            'meta_keywords' => 'Meta Keywords',
            'price' => 'Цена',
            'description' => 'Description',
            'cashback' => 'Cashback',
            'casino_id' => 'Casino ID',
            'service_id'=>'Услуги'
        ];
    }

public function load($data, $formName = null)
{


   if(isset($data['Products']['service_id'])) {
       $this->service_id = $data['Products']['service_id'];
   }
    return parent::load($data, $formName); // TODO: Change the autogenerated stub
}

    public  function afterSave($insert, $changedAttributes)
{
    ProductsServices::deleteAll(['id_product'=>$this->id]);
   if($this->service_id !== null){


        foreach ($this->service_id as $key=>$value):
            $products_services= new ProductsServices();
            $products_services->setAttributes(['id_service'=>$value, 'id_product'=>$this->id],true);
            $products_services->save();

        endforeach;
    }
    parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
}

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCasino()
    {
        return $this->hasOne(Casino::className(), ['id' => 'casino_id']);
    }
public function hasService($service_id){
      return  $this->getProductsServices()->andWhere(['id_service'=>$service_id])->one();
}
   public function   getProductsServices(){
       return $this->hasMany(ProductsServices::className(), ['id_product' => 'id']);
   }
}
