<?php

namespace app\models;

use Yii;
use app\models\base\Banners as BaseBanners;

use yii\helpers\ArrayHelper;
use app\core\ImageClass;
use yii\web\UploadedFile;

/**
 * This is the model class for table "modules_banner".
 *
 * @property integer $id
 * @property string $title
 * @property integer $img_url
 */
class Banners extends BaseBanners
{
    public $imageFile;


    /**
     * @inheritdoc
     */
    /*
    * Проверка на ввод данных + обязательные поля
    */
    public function rules()
    {
        return [[['title', 'img_url'], 'required'],
            [['url'], 'url', 'defaultScheme' => 'http'],
            [['imageFile'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Название баннера (партнера)',
            'url' => 'URL баннера (партнера)'
        ];
    }

    public function saveImage()
    {
        $imgUpload = new ImageClass();
        return $path = $imgUpload->uploadImage(UploadedFile::getInstance($this, 'imageFile'), 'banner/');
    }

    public function load($data, $formName = null)
    {
        if (UploadedFile::getInstance($this, 'imageFile') !== null) {

            $img_url_path = $this->saveImage();
            $this->setAttribute('img_url', $img_url_path);
        }
        return parent::load($data, $formName); // TODO: Change the autogenerated stub
    }



    public function beforeDelete()
    {
        $imgDelete = new ImageClass();
        $imgDelete->deleteImage($this->img_url);
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }


}
