<?php

namespace app\models;

use Yii;
use app\models\base\Coupon as BaseCoupon;
use yii\base\Security;
/**
 * This is the model class for table "coupon".
 *
 * @property integer $id
 * @property integer $coupon
 * @property integer $product_id
 *
 * @property Products $product
 * @property Order[] $orders
 */
class Coupon extends BaseCoupon
{
    private $security;
    public function rules()
    {
        return [
            [[ 'order_id'], 'integer'],
            [['coupon'], 'string'],
            [['status'], 'boolean'],
            [['coupon', 'order_id', 'status'], 'required'],

        ];
    }

    public function __construct(array $config = [])
    {

        $this->security =  new Security();
        parent::__construct($config);
    }
    private function generateCoupon($order_id){
        $coupon = $this->security->generateRandomString(6).$order_id;

      return  $coupon;


    }
    /* method saveCoupon
     * @return $id| false
     */

  public  function saveCoupon($order_id){
       $this->coupon= $this->generateCoupon($order_id);
      $this->order_id= $order_id;
      $this->status= false;


     if ($this->save()){
        return   array('coupon'=>$this->coupon);
     }
     else {
         return false;
     }
    }

    public function save($runValidation = true, $attributeNames = null)
    {
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }
}
