<?php

namespace app\models;

use Yii;
use app\models\base\Coupon as BaseCoupon;
use yii\base\Security;
use app\models\User;
use yii\helpers\Html;

/**
 * This is the model class for table "coupon".
 *
 * @property integer $id
 * @property integer $coupon
 * @property integer $product_id
 *
 * @property Products $product
 * @property Order[] $orders
 */
class Coupon extends BaseCoupon
{
    private $security;
    const USED = 1;
    const UNUSED = 0;

    public function rules()
    {
        return [
            [['coupon'], 'string'],
            [['status'], 'boolean'],
            [['coupon', 'status'], 'required'],

        ];
    }
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'coupon' => 'Купон',
            'order_id' => 'Заказ №',
            'status'=> 'Статус купона',
        ];
    }


    public function __construct(array $config = [])
    {

        $this->security = new Security();
        parent::__construct($config);
    }

    private function generateCoupon($order_id)
    {
        $coupon = $this->security->generateRandomString(6) . $order_id;

        return $coupon;


    }

    /* method saveCoupon
     * @return $id| false
     */

    public function saveCoupon($order_id)
    {
        $this->coupon = $this->generateCoupon($order_id);
        $this->status = false;

        if ($this->save()) {
            return array('id' => $this->id, 'coupon' => $this->coupon);
        } else {
            return false;
        }
    }

    public function save($runValidation = true, $attributeNames = null)
    {
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }
    // Вывод ссылки на Пользователя на странице Купона
    // return Html::a()
    public static function getCouponUserLink($id){
       $user_id = Order::find(['==','coupon_id',$id])->one()->user_id;

      $username= User::findOne($user_id)->username;

      return Html::a($username,'/admin/users/view?id='.$user_id);

    }
// Вывод стоимости Заказа на странице Купона
    // return Order->amount
    public static function getCouponPrice($id){
      return Order::find(['==','coupon_id',$id])->one()->amount;
    }

    // Вывод сылки на  Продукт на странице Купона
    // return Html::a()
    public static function getCouponOrder($id){

     $product_id = Order::find(['==','coupon_id',$id])->one()->product_id;
     $product_title = Products::find($product_id)->one()->title;
        return Html::a($product_title,'/admin/products/view?id='.$product_id);
    }
}
