<?php

namespace app\models;

use Yii;
use app\models\base\ImgProducts  as BaseImgProducts;
use noam148\imagemanager;
/**
 * This is the model class for table "img_casino".
 *
 * @property integer $id
 * @property integer $product_id
 * @property string $img_url
 * @property integer $main_image
 *
 * @property Casino $id0
 */
class ImgProducts extends BaseImgProducts
{




    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'product_id' => 'Бонус-план',
            'img_url' => 'Изображение'
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProducts()
    {
        return $this->hasOne(Products::className(), ['id' => 'product_id']);
    }
    public function load($data, $formName = null)
    {


        return parent::load($data, $formName); // TODO: Change the autogenerated stub
    }
    public function save($runValidation = true, $attributeNames = null)
    {

        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }
}
