<?php

namespace app\models;
use  app\models\base\Order as BaseOrder;
use function Sodium\randombytes_buf;
use Yii;
use app\models\User;
use app\models\Products;
use app\models\Coupon;
use yii\base\Security;
class Order extends BaseOrder
{
private $security;

public function __construct(array $config = [])
{
    $this->security =  new Security();
    parent::__construct($config);
}

    public function rules()
    {
        return [
            [['user_id', 'coupon_id', 'transaction_id'], 'integer'],
            [['paid'], 'boolean'],
            [['product_id', 'amount', 'coupon_id', 'user_id', 'transaction_id', 'paid'], 'required'],
            [['amount'], 'number'],
            [['created_at'], 'safe'], //datetime
            [['product_id'], 'exist', 'skipOnError' => true, 'targetClass' => Products::className(), 'targetAttribute' => ['product_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    public function scenarios()
 {
   $scenarios = parent::scenarios();
     $scenarios['create_order'] = ['user_id','amount', 'created_at', 'product_id', 'paid'];//Scenario Values Only Accepted
     // ToDo: Дополнительные поля Завершения оплаты
     $scenarios['payment'] = ['transaction_id', 'paid'];//Scenario Values Only Accepted
        return $scenarios;

 }



    public function load($data, $formName = null)
    {


$this->create_order($data);

        return parent::load($data, $formName); // TODO: Change the autogenerated stub
    }



    private function create_order($data){
        $this->user_id = Yii::$app->user->identity->id;
        $this->product_id = $data['Products']['id'];
       $this->amount = $data['Products']['price'];
       $this->paid = false;
       $this->transaction_id= null;
    }

    public function payment($data){

//Begin;
// ToDo: для песочницы
        $this->transaction_id=   mt_rand(100,1000);
        // End;
        $coupon = new Coupon();
        $response = $coupon->saveCoupon($data['id']);
        if ($response !== false) {
            Order::updateAll(['transaction_id' => $this->transaction_id, 'paid' => true, 'coupon_id'=> $response['id']], ['=', 'id', $data['id']]);
        }
return $response;



    }


}
