<?php

namespace app\models;
use  app\models\base\Order as BaseOrder;
use Yii;

/**
 * This is the model class for table "order".
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $coupon_id
 * @property string $amount
 * @property string $created_at
 *
 * @property User $user
 * @property Coupon $coupon
 */
class Order extends BaseOrder
{

    public function createOrder(){
$this->coupon_id;
$this->user_id;

    }
    public function save($runValidation = true, $attributeNames = null)

    {

        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }


}
