<?php
namespace app\models;

use Yii;
use app\models\base\OurPartner as BaseOurPartner;
use yii\helpers\ArrayHelper;
use app\core\ImageClass;
use yii\web\UploadedFile;

class OurPartner extends  BaseOurPartner{
    public $imageFile;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'modules_our_partners';
    }
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Название партнера',
            'url'=> 'URL партнера'

        ];
    }
    /*
    * Проверка на ввод данных + обязательные поля
    */
    public function rules()
    {
        return [[['title','url', 'img_url'],'required'],
            [['imageFile'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],

        ];
    }
    public function saveImage()
    {
        $imgUpload =  new ImageClass();

      return  $path = $imgUpload->uploadImage(UploadedFile::getInstance($this, 'imageFile'), 'sliders/');



    }
public function load($data, $formName = null)
{
    if(UploadedFile::getInstance($this, 'imageFile')!==null){
        //ToDo: Сделать Проверку на исключения
 $img_url_path =$this->saveImage();
        $this->setAttribute('img_url', $img_url_path);


    }

    return parent::load($data, $formName); // TODO: Change the autogenerated stub
}






}