<?php

namespace app\models;

use app\models\base\Page as BasePage;
use Yii;

/**
 * This is the model class for table "page".
 *
 * @property integer $id
 * @property string $title
 * @property string $meta_description
 * @property string $meta_keywords
 * @property string $content
 * @property string $date
 */
class Page extends BasePage
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'page';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'meta_description', 'meta_keywords', 'content'], 'required'],
            [['content'], 'string'],
            [['date'], 'safe'],
            [['title', 'meta_description', 'meta_keywords'], 'string', 'max' => 225],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'meta_description' => 'Meta Description',
            'meta_keywords' => 'Meta Keywords',
            'content' => 'Content',
            'date' => 'Date',
        ];
    }


    public function save($runValidation = true, $attributeNames = null)
    {
        $this->date = Yii::$app->formatter->asDate('now', 'yyyy-MM-dd h:i:s');


        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }

}
