<?php

namespace app\models;

use Yii;
use  app\models\base\Slaidshow as BaseSlaidshow;
use yii\helpers\ArrayHelper;
use app\core\ImageClass;
use yii\web\UploadedFile;


/**
 * This is the model class for table "modules_slaidshow".
 *
 * @property integer $id
 * @property string $title
 * @property string $content
 * @property string $img_url
 * @property string $url
 * @property integer $block
 */
class Slaidshow extends BaseSlaidshow
{
    public $imageFile;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'modules_slaidshow';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'content', 'imageFile'], 'required'],
            [['imageFile'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
            [['title', 'content', 'img_url'], 'string', 'max' => 225],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Заголовок',
            'content' => 'Содержимое',
            'img_url' => 'Изображение'
        ];
    }
    public function saveImage()
    {

        $imgUpload = new ImageClass();
        return $path = $imgUpload->uploadImage(UploadedFile::getInstance($this, 'imageFile'), 'banner/');


    }

    public function save($runValidation = true, $attributeNames = null)
    {
        if (UploadedFile::getInstance($this, 'imageFile') !== null) {

            $img_url_path = $this->saveImage();
            $this->setAttribute('img_url', $img_url_path);
        }



        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }
}
